# Site
name: 'Waylin Lim'
description: 'Just do it.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/Waylin-Lim.github.io'
disqus: 'demowebsite'
email: '1079320517@qq.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Waylin:
      name:           Waylin
      site:           https://www.kuntok.com
      avatar:         /assets/images/Waylin_201812051108.jpg
      bio:            "Hi, I am Waylin, the author of this blog, the blog you're currently previewing. I hope you like it!"
      email:          1079320517@qq.com
      twitter:        https://twitter.com/WaylinLim

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
