# Site
name: 'Waylin Lim'
description: 'Just do it.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/Waylin-Lim.github.io'
disqus: 'Waylin's personal blog'
email: '1079320517@qq.com'
mailchimp-list: 'https://us4.admin.mailchimp.com/account/connected-sites/site-detail?id=13071'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Waylin:
      name:           Waylin
      site:           https://www.kuntok.com
      avatar:         /assets/images/Waylin_201812051108.jpg
      bio:            "Hi, I am Waylin, the author of this blog you're currently previewing. I hope you like it!"
      email:          1079320517@qq.com
      linkedin:       https://www.linkedin.com/in/waylin-lim-39a4b5110/
      twitter:        https://twitter.com/WaylinLim
      facebook:       https://www.facebook.com/WaylinLimCN

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Waylin
      avatar: /assets/images/Waylin_201812051108.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
